(** Encoding job arguments to and from JSON.

    Job arguments are persisted as JSON so that any node that knows the job's
    name can decode and execute them. Keep argument types small and stable: they
    are part of your wire format across deploys. *)

type 'a t = {
  encode : 'a -> Yojson.Safe.t;
  decode : Yojson.Safe.t -> ('a, string) result;
}

val make :
  encode:('a -> Yojson.Safe.t) ->
  decode:(Yojson.Safe.t -> ('a, string) result) ->
  'a t

val of_yojson :
  ('a -> Yojson.Safe.t) -> (Yojson.Safe.t -> ('a, string) result) -> 'a t
(** [of_yojson to_yojson of_yojson] adapts the functions generated by
    [[@@deriving yojson]]. *)

val unit : unit t
val string : string t
val int : int t

val json : Yojson.Safe.t t
(** The identity codec, for jobs that interpret raw JSON themselves. *)
